# -------------------- Import Libraries --------------------
import argparse
from Bio import SeqIO

# ----------------------------------------------------------
# Command line arguments
# ----------------------------------------------------------
# This allows the script to be run from the command line
parser = argparse.ArgumentParser(description="Generate gene presence/absence profiles from GenBank files.")

# Required arguments
parser.add_argument("--input", required=True, help="Input GenBank (.gbk) file")
parser.add_argument("--tsv", required=True, help="Output TSV file for gene profiles")

# Optional argument
parser.add_argument("-n", "--nexus", help="Optional Nexus-style output text file")

# Parse the arguments
args = parser.parse_args()

# Access arguments
input_file = args.input
tsv_file = args.tsv
nexus_file = args.nexus


# ----------------------------------------------------------
# Read the big genbank file generated by fetchGenbank.py
# ----------------------------------------------------------

# make a dictionary out of the genbank files
# the genbank IDs are the keys and the other features of the genbank files as values

try:
    sequence_dict = SeqIO.to_dict(SeqIO.parse(input_file, "genbank"))
except Exception as e:
    print(f"Error reading GenBank file: {e}")
    sequence_dict = {}

print(f"Number of sequences read: {len(sequence_dict)}")

# ----------------------------------------------------------
# Remove sequences that do not have any gene features
# ----------------------------------------------------------

# if a .gbk file has no genes present as features then there is a problem

# make a list of sequences to remove
no_gene_list = []

# figure out if a gene is present
for key, seq_record in sequence_dict.items():
    has_gene = any('gene' in f.qualifiers for f in seq_record.features)
    if not has_gene:
        no_gene_list.append(key)
        
# remove sequences records from the dictionary if there is no gene        
for key in no_gene_list:
    sequence_dict.pop(key)

# summary outputs
print(f"Removed {len(no_gene_list)} sequences with no gene annotations.")
# print the genbank IDs that have no gene annotations if there are any
if len(no_gene_list) > 0:
	print (f"These sequences have no gene annotations: {no_gene_list} ")
print(f"Remaining sequences: {len(sequence_dict)}")

# ----------------------------------------------------------
# Extract taxon names, GenBank IDs, genes, and pseudogenes
# ----------------------------------------------------------

# make empty lists to store values in
taxa_names = []
genbank_ids = []
all_present_genes = []
all_pseudogenes = []

# loop over taxa in the dictionary 
for seq_record in sequence_dict.values():
    taxon_name = "_".join(seq_record.description.split()[:2])
    taxa_names.append(taxon_name)
    genbank_ids.append(seq_record.name)
	
    present_genes = []
    pseudogenes = []
	
	# classify the features in the sequence record as genes or pseudogenes
    for f in seq_record.features:
        if 'gene' in f.qualifiers:
            gene_name = ''.join(f.qualifiers['gene']).lower()
            if 'pseudo' in f.qualifiers:
                pseudogenes.append(gene_name)
            else:
                present_genes.append(gene_name)
	
	# remove duplicates (things in the IR will get listed twice)
    present_genes = list(set(present_genes))
    # remove pseudogenes that also exist as functional genes
    pseudogenes = list(set([g for g in pseudogenes if g not in present_genes]))
	
    all_present_genes.append(present_genes)
    all_pseudogenes.append(pseudogenes)

# summary data
print(f"Extracted gene data for {len(taxa_names)} taxa.")


# ----------------------------------------------------------
# Define reference gene lists
# ----------------------------------------------------------

# genes come in lots of different spelling variations so need to catch them all 
# input the list of genes as a string and break it up into a list by the tabs in between 
geneString = "ndhA	ndhB	ndhC	ndhD	ndhE	ndhF	ndhG	ndhH	ndhI	ndhJ	ndhK	ccsA	cemA	petA	petB	petD	petG	petL	petN	psaA	psaB	psaC	psaI	psaJ	psbA	psbB	psbC	psbD	psbE	psbF	psbH	psbI	psbJ	psbK	psbL	psbM	psbN	psbT	psbZ	rbcL	ycf3	ycf4	rpoA	rpoB	rpoC1	rpoC2	atpA	atpB	atpE	atpF	atpH	atpI	infA	rpl2	rpl14	rpl16	rpl20	rpl22	rpl23	rpl32	rpl33	rpl36	rps2	rps3	rps4	rps7	rps8	rps11	rps12	rps14	rps15	rps16	rps18	rps19	accD	clpP	matK	ycf1	ycf2	rrn4.5	rrn5	rrn16	rrn23	trnA-UGC	trnC-GCA	trnD-GUC	trnE-UUC	trnF-GAA	trnfM-CAU	trnG-GCC	trnG-UCC	trnH-GUG	trnI-CAU	trnI-GAU	trnK-UUU	trnL-CAA	trnL-UAA	trnL-UAG	trnM-CAU	trnN-GUU	trnP-UGG	trnQ-UUG	trnR-ACG	trnR-UCU	trnS-GCU	trnS-GGA	trnS-UGA	trnT-GGU	trnT-UGU	trnV-GAC	trnV-UAC	trnW-CCA	trnY-GUA"
gene_list = geneString.split('\t')
# extract the tRNA list
trna_list = gene_list[83:]
# extract the rrna list
rrna_list = gene_list[79:83]
# extract the protein coding gene list
geneList = gene_list[:79]

# have only seen this style in one genbank file (Sesamum) but it's strange and must be spelled out in full
trna_sesamum_list = ['tRNA-Ala (UGC)', 'tRNA-Cys (GCA)', 'tRNA-Asp (GUC)', 'tRNA-Glu (UUC)', 'tRNA-Phe (GAA)', 'tRNA-fM (CAU)', 'tRNA-Gly (GCC)', 'tRNA-Gly (UCC)', 'tRNA-His (GUG)', 'tRNA-Ile (CAU)', 'tRNA-Ile (GAU)', 'tRNA-Lys (UUU)', 'tRNA-Leu (CAA)', 'tRNA-Leu (UAA)', 'tRNA-Leu (UAG)', 'tRNA-Met (CAU)', 'tRNA-Asn (GUU)', 'tRNA-Pro (UGG)', 'tRNA-Gln (UUG)', 'tRNA-Arg (ACG)', 'tRNA-Arg (UCU)', 'tRNA-Ser (GCU)', 'tRNA-Ser (GGA)', 'tRNA-Ser (UGA)', 'tRNA-Thr (GGU)', 'tRNA-Thr (UGU)', 'tRNA-Val (GAC)', 'tRNA-Val (UAC)', 'tRNA-Trp (CCA)', 'tRNA-Tyr (GUA)']

# write out alternative rrna gene name formats
rrna_word_list = ['23S rRNA', '4.5S rRNA', '5S rRNA', '16S rRNA']
rrn_alternate_list = ['rrn16', 'rrn4.5s', 'rrn5s', 'rrn23s']

# make everything lowercase for case insensitive matching
gene_list = [g.lower() for g in gene_list]
rrna_list = [g.lower() for g in rrna_list]
trna_list = [g.lower() for g in trna_list]
trna_sesamum_list = [g.lower() for g in trna_sesamum_list]


# ----------------------------------------------------------
# Generate alternative tRNA spellings
# ----------------------------------------------------------

# make empty lists for alternate spellings of tRNA genes
trna_hyphen = []
trna_underscore = []
trna_bracket = []
trna_no_punct = []

# make the alternate trna spellings
for gene in trna_list:
    trna_hyphen.append(gene)
    trna_underscore.append(gene.replace('-', '_'))
    trna_bracket.append(gene.replace('-', '(') + ")")
    trna_no_punct.append(gene.replace('-', '').replace('(', '').replace(')', ''))


# ----------------------------------------------------------
# Generate gene presence/absence profiles
# ----------------------------------------------------------

# a 0 represents that a gene is present
# a 1 represents that a gene is absent 
# a 2 represents that a gene is a pseudogene

#empty list for gene presence absence profiles
gene_profiles = []

for i in range(len(sequence_dict)):
    profile = []

    #  go through the protein coding genes
    for gene in gene_list:
        if gene in all_pseudogenes[i]:
            profile.append("2")
        elif gene in all_present_genes[i]:
            profile.append("0")
        else:
            profile.append("1")

    # go through the rRNAs
#     for rrna in rrna_list:
#         if rrna in all_pseudogenes[i]:
#             profile.append("2")
#         elif rrna in all_present_genes[i]:
#             profile.append("0")
#         else:
#             profile.append("1")
            
    # go through the rRNAs
    for j in range(len(rrna_list)):
        found = False
        for variant_list in [rrn_alternate_list, rrna_word_list, rrna_list]:
            if variant_list[j] in all_pseudogenes[i]:
                profile.append("2")
                found = True
                break
        if not found:
       		for variant_list in [rrn_alternate_list, rrna_word_list, rrna_list]:
       			if variant_list[j] in all_present_genes[i]:
       				profile.append("0")
       				found = True
       				break
       	if not found:
       		profile.append("1")         

    # go through the tRNAs
    for j in range(len(trna_list)):
        found = False
        for variant_list in [trna_hyphen, trna_underscore, trna_bracket, trna_no_punct, trna_sesamum_list]:
            if variant_list[j] in all_pseudogenes[i]:
                profile.append("2")
                found = True
                break
        if not found:
            for variant_list in [trna_hyphen, trna_underscore, trna_bracket, trna_no_punct, trna_sesamum_list]:
                if variant_list[j] in all_present_genes[i]:
                    profile.append("0")
                    found = True
                    break
        if not found:
            profile.append("1")
    gene_profiles.append(profile)

print("Gene presence/absence profiles generated.")

# ----------------------------------------------------------
# make a nexus style output
# ----------------------------------------------------------

# the nexus file style output is optional and will only be generated if specified on the command line
# useful if using the same species (with the same names) to make a phylogeny
# can use this block for character state mapping e.g. in Mesquite

if nexus_file:
    longest_taxon = max(taxa_names, key=len)
    with open(nexus_file, "w") as f:
        for i, profile in enumerate(gene_profiles):
            f.write(taxa_names[i].ljust(len(longest_taxon) + 5) + "".join(profile) + "\n")
    print(f"Nexus-style text file written: {nexus_file}")


# ----------------------------------------------------------
# Make a tabular output
# ----------------------------------------------------------
with open(tsv_file, "w") as f:
    f.write("speciesName\tgenbankID\t" + "\t".join(gene_list + rrna_list + trna_list) + "\n")
    for i in range(len(taxa_names)):
        f.write(f"{taxa_names[i]}\t{genbank_ids[i]}\t" + "\t".join(gene_profiles[i]) + "\n")

print(f"TSV file written: {tsv_file}")
print("Processing complete.")
