####################################################################################################
# This script:
# 1. Reads in a multi-sequence .gbk file
# 2. Parses annotations in the .gbk file by taxon
# 3. Creates a TSV stating whether a gene is present, missing, or pseudogenized
# 4. Optionally makes a nexus-style text block for character state mapping
####################################################################################################

# ----------------------------------------------------------
# Import packages
# ----------------------------------------------------------

import argparse
import re
from Bio import SeqIO


# ----------------------------------------------------------
# Command line arguments
# ----------------------------------------------------------

# This allows the script to be run from the command line
parser = argparse.ArgumentParser(
    description="Generate gene presence/absence profiles from GenBank files."
)

# Required arguments
parser.add_argument("--input", required=True, help="Input GenBank (.gbk) file")
parser.add_argument("--tsv", required=True, help="Output TSV file for gene profiles")

# Optional arguments
parser.add_argument("--gene_file", help="Optional file containing one gene per line (overrides default list)")
parser.add_argument("-n", "--nexus", help="Optional nexus-style block output in text file")

# Parse the arguments
args = parser.parse_args()

# Access arguments
input_file = args.input
tsv_file = args.tsv
gene_file = args.gene_file
nexus_file = args.nexus


# ----------------------------------------------------------
# Read the big genbank file generated by fetchGenbank.py
# ----------------------------------------------------------

# make a dictionary out of the genbank files
# the genbank IDs are the keys and the other features of the genbank files as values

try:
    sequence_dict = SeqIO.to_dict(SeqIO.parse(input_file, "genbank"))
except Exception as e:
    print(f"Error reading GenBank file: {e}")
    sequence_dict = {}

print(f"Number of sequences read: {len(sequence_dict)}")


# ----------------------------------------------------------
# Remove sequences without gene annotations
# ----------------------------------------------------------

# if a .gbk file has no genes present as features then there is a problem

# make a list of sequences to remove
no_gene_list = []

# figure out if a gene is present
for key, seq_record in sequence_dict.items():
    has_gene = any("gene" in f.qualifiers for f in seq_record.features)
    if not has_gene:
        no_gene_list.append(key)

# remove sequences records from the dictionary if there is no gene        
for key in no_gene_list:
    sequence_dict.pop(key)

# summary outputs
print(f"Removed {len(no_gene_list)} sequences with no gene annotations.")
# print the genbank IDs that have no gene annotations if there are any
if len(no_gene_list) > 0:
    print(f"These sequences have no gene annotations: {no_gene_list}")
print(f"Remaining sequences: {len(sequence_dict)}")


# ----------------------------------------------------------
# Define reference gene list (default or optional override)
# ----------------------------------------------------------

# Add in the default genes tested (canonical angiosperm plastid genes)
default_gene_string = (
    "ndhA\tndhB\tndhC\tndhD\tndhE\tndhF\tndhG\tndhH\tndhI\tndhJ\tndhK\t"
    "ccsA\tcemA\tpetA\tpetB\tpetD\tpetG\tpetL\tpetN\t"
    "psaA\tpsaB\tpsaC\tpsaI\tpsaJ\t"
    "psbA\tpsbB\tpsbC\tpsbD\tpsbE\tpsbF\tpsbH\tpsbI\tpsbJ\tpsbK\tpsbL\tpsbM\tpsbN\tpsbT\tpsbZ\t"
    "rbcL\tycf3\tycf4\t"
    "rpoA\trpoB\trpoC1\trpoC2\t"
    "atpA\tatpB\tatpE\tatpF\tatpH\tatpI\t"
    "infA\t"
    "rpl2\trpl14\trpl16\trpl20\trpl22\trpl23\trpl32\trpl33\trpl36\t"
    "rps2\trps3\trps4\trps7\trps8\trps11\trps12\trps14\trps15\trps16\trps18\trps19\t"
    "accD\tclpP\tmatK\tycf1\tycf2\t"
    "rrn4.5\trrn5\trrn16\trrn23\t"
    "trnA-UGC\ttrnC-GCA\ttrnD-GUC\ttrnE-UUC\ttrnF-GAA\ttrnfM-CAU\t"
    "trnG-GCC\ttrnG-UCC\ttrnH-GUG\ttrnI-CAU\ttrnI-GAU\ttrnK-UUU\t"
    "trnL-CAA\ttrnL-UAA\ttrnL-UAG\ttrnM-CAU\ttrnN-GUU\ttrnP-UGG\t"
    "trnQ-UUG\ttrnR-ACG\ttrnR-UCU\ttrnS-GCU\ttrnS-GGA\ttrnS-UGA\t"
    "trnT-GGU\ttrnT-UGU\ttrnV-GAC\ttrnV-UAC\ttrnW-CCA\ttrnY-GUA")

# Default gene list
gene_list = default_gene_string.split("\t")

# Optional override if user is inputting their own gene list
if gene_file:
    with open(gene_file) as gf:
        gene_list = [line.strip() for line in gf if line.strip()]
    print(f"Using custom gene list from {gene_file}")
else:
    print("Using default hard-coded chloroplast gene list")

canonical_genes = gene_list
print(f"Tracking {len(canonical_genes)} genes.")


# ----------------------------------------------------------
# Build normalized lookup dictionary
# ----------------------------------------------------------

normalized_targets = {}

# Strip punctuation and white space from gene names in order to normalise them
for g in canonical_genes:
    norm = g.lower()
    norm = re.sub(r'[\s_\-()]', '', norm)
    norm = norm.replace("rna", "")
    normalized_targets[norm] = g
    

# ----------------------------------------------------------
# Extract taxon names, GenBank IDs, genes, and pseudogenes
# ----------------------------------------------------------

# make empty lists to store values in
taxa_names = []
genbank_ids = []
all_present_genes = []
all_pseudogenes = []

# loop over taxa in the dictionary 
for seq_record in sequence_dict.values():
	# extract taxon name from genabnk record
    taxon_name = "_".join(seq_record.description.split()[:2])
    taxa_names.append(taxon_name)
    genbank_ids.append(seq_record.name)
	# establish empty lists to be filled in
    present_genes = set()
    pseudogenes = set()
	# loop through the features in the sequence and record as genes or pseudogenes
    for f in seq_record.features:
    	# only consider sequences that could be relevant
        if f.type in ["CDS", "tRNA", "rRNA", "gene"]:
            gene_qual = f.qualifiers.get("gene", [""])[0]
            product_qual = f.qualifiers.get("product", [""])[0]
            combined_name = gene_qual if gene_qual else product_qual
			# if no name match then move on
            if not combined_name:
                continue
			# normalise the spelling names in the same way as above to find a match
            norm_name = combined_name.lower()
            # special case for some rrna spellings where whole word is used 
            rrna_match = re.search(r'(\d+(?:\.\d+)?)s\s+ribosomal', norm_name)
            if rrna_match:
            	number = rrna_match.group(1)
            	norm_name = f"rrn{number}"
			# standard normalisation for everything else
            else:
            	norm_name = re.sub(r'[\s_\-()]', '', norm_name)
            	# removes s from the end of e.g. rrn16s
            	norm_name = re.sub(r'rrn(\d+(?:\.\d+)?)s$', r'rrn\1', norm_name)
            	norm_name = norm_name.replace("rna", "")
            if norm_name in normalized_targets:
                canonical = normalized_targets[norm_name]
				# if there's pseudo in the gene information, classify it as a pseudogene
                if "pseudo" in f.qualifiers:
                    pseudogenes.add(canonical)
                else:
                    present_genes.add(canonical)
	# if a gene is included in pseudogenes and present genes, remove it from pseudogenes
	# potentially could be an issue if partial copies are present and the end of one IR
    pseudogenes = pseudogenes - present_genes
    all_present_genes.append(present_genes)
    all_pseudogenes.append(pseudogenes)

print(f"Extracted gene data for {len(taxa_names)} taxa.")


# ----------------------------------------------------------
# Generate gene presence/absence profiles
# ----------------------------------------------------------

gene_profiles = []

for i in range(len(taxa_names)):
    profile = []
    for gene in canonical_genes:
        if gene in all_pseudogenes[i]:
            profile.append("2")
        elif gene in all_present_genes[i]:
            profile.append("0")
        else:
            profile.append("1")
    gene_profiles.append(profile)

print("Gene presence/absence profiles generated.")


# ----------------------------------------------------------
# Optional nexus-style output
# ----------------------------------------------------------

# the nexus file style output is optional and will only be generated if specified on the command line
# useful if using the same species (with the same names) to make a phylogeny
# can use this block for character state mapping e.g. in Mesquite

if nexus_file:
    longest_taxon = max(taxa_names, key=len)
    with open(nexus_file, "w") as f:
        for i, profile in enumerate(gene_profiles):
            f.write(taxa_names[i].ljust(len(longest_taxon) + 5) + "".join(profile) + "\n")
    print(f"Nexus-style text file written: {nexus_file}")


# ----------------------------------------------------------
# Write TSV output
# ----------------------------------------------------------

with open(tsv_file, "w") as f:
    f.write("speciesName\tgenbankID\t" + "\t".join(canonical_genes) + "\n")
    for i in range(len(taxa_names)):
        f.write( f"{taxa_names[i]}\t{genbank_ids[i]}\t" + "\t".join(gene_profiles[i]) + "\n")

print(f"TSV file written: {tsv_file}")
print("Processing complete.")
