###############################################################################################################################
# This script:
# 1. Reads the presence/absence .TSV produced by the gene profiling script
# 2. Reads in the alignment files generated by aligner.py
# 3. extracts the gene/taxon combinations and evaluates the hits (sequences in the alignment)
# 4. Determines if the hit found by blast is a pseudogene or a full gene, or if something annotated as a pseudogene is actually missing
# 5. Writes out the results to a new presence/absence .TSV
# 6. Makes a change log TSV to show which genes had values changed for which taxa
###############################################################################################################################


# =============================================================================================================================
# Import packages
# =============================================================================================================================

import os
import argparse
import pandas as pd

# =============================================================================================================================
# Argument parsing
# =============================================================================================================================

parser = argparse.ArgumentParser(description="Update presence/absence TSV based on alignment evidence.")

parser.add_argument("--ogTSV", required=True,
                    help="Original presence/absence TSV file")

parser.add_argument("--alignDir", required=True,
                    help="Directory containing gene alignment folders (default: alignments)")

parser.add_argument("--outTSV", default="updatedPA.tsv",
                    help="Output updated TSV file name (default: updatedPA.tsv)")

parser.add_argument("--changeLog", default="changeLog.tsv",
                    help="File to record changes made (default: changeLog.tsv)")

parser.add_argument("--minCov", type=float, default=0.95,
                    help="Minimum coverage to call a gene present (default: 0.95)")

parser.add_argument("--minSim", type=float, default=0.95,
                    help="Minimum similarity to call a gene present (default: 0.95)")

args = parser.parse_args()

# read the original presence/absence TSV
df = pd.read_csv(args.ogTSV, sep="\t")

# make an empty list to store changes made to the original TSV in
changes = []

# =============================================================================================================================
# Iterate over each gene in the dataframe
# =============================================================================================================================

# column 0 is the species name, column 1 is the genbank ID, so column 2 is where gene names start
for gene in df.columns[2:]:

    # alignments are stored in folders named after the lowercase gene + "-alignment"
    gene_folder_name = gene.lower() + "-alignment"
    gene_folder = os.path.join(args.alignDir, gene_folder_name)

    if not os.path.isdir(gene_folder):
        # Skip if no alignment folder exists for this gene
        continue

    # collect fasta alignment files (ignore reference-only files)
    fasta_files = [f for f in os.listdir(gene_folder)
                   if f.endswith("aln.fa") and "ref_only" not in f]

    # step for debugging
    # print("Alignment files found for", gene, ":", fasta_files)

    # skip the gene if no .aln.fa alignment fasta files are found
    if len(fasta_files) == 0:
        continue

    # when there are more myultiple alignments, assess in this order; codon > protein > nucleotide
    fasta_files.sort(reverse=True)
    fasta_path = os.path.join(gene_folder, fasta_files[0])

    # dictionary to store sequences keyed by GenBank ID
    sequences = {}
    # to hold the reference sequence       
    reference_seq = None 

    # =============================================================================================================================
    # Read alignment file
    # =============================================================================================================================
    
    # read alignment files one at a time
    with open(fasta_path) as f:
        header = None
        seq_lines = []

        for line in f:
            # remove any trailing white space
            line = line.strip()
            # process the header
            if line.startswith(">"):
                # Process the previous sequence before moving to next header
                # if there is not a header (i.e. sequence data) join all lines of sequence together into one string
                if header:
                    sequence = "".join(seq_lines)
                    
                    # basically skip genes annotated as pseudogenes on GenBank as pseudogenes if user chooses to add them into the alignment
                    if "pseudogene" in header.lower():
                        header = line[1:]
                        seq_lines = []
                        continue
                    # sequences found through BLAST will have "|" character based on how i wrote the output
                    if "|" in header:
                        # extract GenBank ID from header
                        # all made in same format from previous scripts so parsing can be automated like this
                        parts = header.split("|")
                        genbank = parts[0].split(".")[0]
                        # some gene alignments will have multiple sequences per sequence
                        sequences.setdefault(genbank, []).append(sequence)
                    else:
                        # reference sequences should not have the "|" character based on how i wrote the scripts
                        reference_seq = sequence
                # Remove ">" from header
                header = line[1:]  
                seq_lines = []
            else:
                seq_lines.append(line)

        # Process the last sequence in the file (previous block set up to process a sequence by finding the next header)
        if header:
            sequence = "".join(seq_lines)
            if "pseudogene" not in header.lower():
                if "|" in header:
                    parts = header.split("|")
                    genbank = parts[0].split(".")[0]
                    sequences.setdefault(genbank, []).append(sequence)
                else:
                    reference_seq = sequence

    # this should never happen based on how I constructed pipeline but including it just in case
    if reference_seq is None:
        # Skip gene if no reference sequence is found
        continue

    # remove gaps from the refernce sequences to understand the true length of the gene
    ungapped_ref = reference_seq.replace("-", "")
    ref_length = len(ungapped_ref)

    # identify if gene codes for RNA (trna or rna)
    is_rna = gene.startswith("trn") or gene.startswith("rrn")

    # =============================================================================================================================
    # Evaluate each species' genbank annotations with the input TSV
    # =============================================================================================================================
    
    # loop over all rows in the dataframe (input TSV)
    for idx in df.index:

        # determine what the original gene values were according to genbank annotations
        original_value = df.loc[idx, gene]
        # remove genbank ID suffix (sometimes there are decimals after the ID)
        genbank_id = str(df.loc[idx, "genbankID"]).split(".")[0]
        species_name = df.loc[idx, "speciesName"]

        # Skip genes annotated as present 
        if original_value == 0:
            continue

        # If species has no sequences, upgrade missing/pseudogene to "absent" (1)
        if genbank_id not in sequences:
            # only add to the change file if it's actually a change
            if original_value != 1:
                old_val = original_value
                df.loc[idx, gene] = 1
                changes.append([species_name, genbank_id, gene, old_val, 1, "no_sequence", None, None])
            # if the value is already set to missing then don't add it to the change file
            continue

        # best scoring sequence for this taxon
        best_seq = None
        # set the scores assessing sequences by to 0/-1 and real values are filled in later        
        best_score = -1
        best_similarity = 0
        best_coverage = 0
        # Tracks if any sequence is usable (e.g. not too long from poor joining of blast hits)
        any_valid = False      

        # =============================================================================================================================
        # Evaluate all sequences for each taxon
        # =============================================================================================================================
        
        # look at the sequences for each genbank ID one at a time
        for seq in sequences[genbank_id]:

            # get the real sequence length by ignoring the gaps
            ungapped_test = seq.replace("-", "")
            test_length = len(ungapped_test)

            # Skip sequences that are too long, but continue checking other hits
            # consider changing this so that it is user defined in arg parse
            if test_length > (1.5 * ref_length):
                continue

            # makes sure that there is at least one usable sequence for this taxon/gene combination
            any_valid = True

            # calculate coverage by comparing ungapped sequence lengths
            coverage = test_length / ref_length
            # calculate similarity by getting propportion of bases that match in the aligned positions
            aligned_positions = 0
            identity = 0
            for r, t in zip(reference_seq, seq):
                if r != "-" and t != "-":
                    aligned_positions += 1
                    if r == t:
                        identity += 1
            similarity = identity / aligned_positions if aligned_positions > 0 else 0

            # the score combines coverage and similarity (at the moment this is weighted in favour of coverage)
            score = (coverage * 0.6) + (similarity * 0.4)

            # Keep the sequence with the best score to evaluate for presence or pseudogene
            if score > best_score:
                best_score = score
                best_seq = seq
                best_similarity = similarity
                best_coverage = coverage

        # if no sequences are valid after skipping long hits then mark the gene as a psedogene
        # hopefully this is unusual
        if not any_valid:
            old_val = original_value
            df.loc[idx, gene] = 2
            changes.append([species_name, genbank_id, gene, old_val, 2, "all_hits_too_long", None, None])
            continue

        # =============================================================================================================================
        # Evaluate best valid sequence
        # =============================================================================================================================
        
        # remove gaps from the chosen best sequence for each taxon
        ungapped_test = best_seq.replace("-", "")
        test_length = len(ungapped_test)
        # determine if there is a frame shift mutations (should be divisible by 3)
        frameshift = (test_length % 3 != 0)
        # determine if there is an internal stop codon (anywhere except the last codon)
        internal_stop = "*" in ungapped_test[:-1]

        # =============================================================================================================================
        # RNA genes
        # =============================================================================================================================
        if is_rna:
            # RNA gene considered present if coverage and similarity >= thresholds
            if best_coverage >= args.minCov and best_similarity >= args.minSim:
                if original_value in [1, 2]:
                    old_val = original_value
                    df.loc[idx, gene] = 0
                    changes.append([species_name, genbank_id, gene, old_val, 0, "gene_present", round(best_coverage,3), round(best_similarity,3)])
            else:
                old_val = original_value
                df.loc[idx, gene] = 2
                if original_value != 2:
                    changes.append([species_name, genbank_id, gene, old_val, 2, "rna_degraded", round(best_coverage,3), round(best_similarity,3)])

        # =============================================================================================================================
        # Protein-coding genes
        # =============================================================================================================================
        else:
            # gene is considered present if there is no frameshift, no internal stop codon, and meets user defined coverage/similarity thresholds
            if (not frameshift) and (not internal_stop) and \
               best_coverage >= args.minCov and best_similarity >= args.minSim:
                if original_value in [1, 2]:
                    old_val = original_value
                    df.loc[idx, gene] = 0
                    changes.append([species_name, genbank_id, gene, old_val, 0, "gene_present", round(best_coverage,3), round(best_similarity,3)])
            # if there's a hit but it doesn't match the above the above conditions still marked as a pseudogene        
            else:
                old_val = original_value
                df.loc[idx, gene] = 2
                if original_value != 2:
                    changes.append([species_name, genbank_id, gene, old_val, 2, "coding_degraded", round(best_coverage,3), round(best_similarity,3)])

# =============================================================================================================================
# Write outputs
# =============================================================================================================================

# Updated presence/absence TSV
df.to_csv(args.outTSV, sep="\t", index=False)

# Change log with coverage and similarity
change_df = pd.DataFrame(changes, columns=[
    "speciesName",
    "genbankID",
    "gene",
    "old_value",
    "new_value",
    "reason",
    "coverage",
    "similarity"])
change_df.to_csv(args.changeLog, sep="\t", index=False)

print("Finished.")
print("Updated TSV written to:", args.outTSV)
print("Change log written to:", args.changeLog)